services:
  app:
    container_name: "backcontainer"
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://dpg-cuosscd6l47c73cglieg-a/pokemon_db_zzzm
      - SPRING_DATABASE_USERNAME=root
      - SPRING_DATABASE_PASSWORD=VgCsev4tdpKhajmrmU86yX0AaTnyakFP
      - SPRING_DATABASE_DRIVER_CLASS_NAME=org.postgresql.Driver
    depends_on:
      postgresdb:
        condition: service_healthy

  postgresdb:
    container_name: "postgresdb"
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "pokemon_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "VgCsev4tdpKhajmrmU86yX0AaTnyakFP"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pokemon_db"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres-data:
    external: false
